name: IC-Essentials
main: com.igneouscraft.plugin.icessentials.ICEssentials
version: 0.3
author: [bl4ckscor3]
description: Adds tons of essentials to the server!
commands:
    example:
        description: Example command.
        usage: /<command>
    icreload:
        description: Reloads the plugin.
        usage: /<command>
    ichelp:
        description: Helps with the plugin.
        usage: /<command>
