name: IC-Essentials
main: net.igneouscraft.plugin.icessentials.ICEssentials
version: 0.6
author: [bl4ckscor3,JustRamon]
description: Adds tons of essentials to the server!
commands:
    example:
        description: Example command.
        usage: /<command>
    icreload:
        description: Reloads the plugin.
        usage: /<command>
    help:
        description: Overrides the default help to include custom help in the same command.
        usage: /<command>
    rb:
        description: Main command.
        usage: /rb <add|abort|remove|start|stop|restart>

permissions:
    icessentials.elytralaunch.iron:
        description: Allows you to use the iron elytra launcher.
        default: op
    icessentials.elytralaunch.gold:
        description: Allows you to use the gold elytra launcher.
        default: op
        children:
            icessentials.elytralaunch.iron: true
    icessentials.elytralaunch.diamond:
        description: Allows you to use the diamond elytra launcher.
        default: op
        children:
            icessentials.elytralaunch.gold: true
    icessentials.rainbowbeacons:
        description: Allows you to manage rainbow beacons.
        default: op
    icessentials.reload:
        description: Allows you to reload IC-Essentials.
        default: op